In [3]:
import pandas as pd
import numpy as np
import random
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from math import sqrt
path_final = 'data_final/'

In [4]:
df_test1 = pd.read_csv(path_final+"test_final_0.csv")
df_test2 = pd.read_csv(path_final+"test_final_5.csv")
df_test3 = pd.read_csv(path_final+"test_final_10.csv")
df_test4 = pd.read_csv(path_final+"test_final_15.csv")
df_train1 = pd.read_csv(path_final+"train_final_0.csv")
df_train2 = pd.read_csv(path_final+"train_final_5.csv")
df_train3 = pd.read_csv(path_final+"train_final_10.csv")
df_train4 = pd.read_csv(path_final+"train_final_15.csv")

In [5]:
df_train_list = [df_train1,df_train2, df_train3, df_train4]
df_test_list = [df_test1, df_test2, df_test3, df_test4]

In [7]:
df_train = pd.concat(df_train_list)

In [8]:
df_train[(df_train['date'] == '2016-10-01') & (df_train['hour'] == 8)].head()

time_start  volume  direction  tollgate_id  \
888   2016-10-01 08:00:00     217          0            1   
889   2016-10-01 08:20:00     210          0            1   
890   2016-10-01 08:40:00     198          0            1   
3480  2016-10-01 08:00:00      14          0            2   
3481  2016-10-01 08:20:00      14          0            2   

              time_window  weekday  weekend  hour        date  \
888   [08:00:00,08:20:00)        6        1     8  2016-10-01   
889   [08:20:00,08:40:00)        6        1     8  2016-10-01   
890   [08:40:00,09:00:00)        6        1     8  2016-10-01   
3480  [08:00:00,08:20:00)        6        1     8  2016-10-01   
3481  [08:20:00,08:40:00)        6        1     8  2016-10-01   

      volume_anterior      ...        media_volume  desvio_padrao  am_pm  \
888             233.0      ...                74.0      80.124902      1   
889             217.0      ...                82.4      71.904798      1   
890             210.0      ...                80.2      67.221276      1   
3480             20.0      ...                75.0      36.687873      1   
3481             14.0      ...                77.4      38.688500      1   

      pressure  sea_pressure  wind_direction  wind_speed  temperature  \
888        NaN           NaN             NaN         NaN          NaN   
889        NaN           NaN             NaN         NaN          NaN   
890        NaN           NaN             NaN         NaN          NaN   
3480       NaN           NaN             NaN         NaN          NaN   
3481       NaN           NaN             NaN         NaN          NaN   

      rel_humidity  precipitation  
888            NaN            NaN  
889            NaN            NaN  
890            NaN            NaN  
3480           NaN            NaN  
3481           NaN            NaN  

[5 rows x 21 columns]

In [9]:
df_remove = df_train.loc[(df_train['date'] >= '2016-10-01') 
                         & (df_train['date'] <= '2016-10-07') 
                        ]

df_train = df_train.drop(df_remove.index)

In [10]:
df_train[(df_train['date'] == '2016-10-01') & (df_train['hour'] == 8)].head()

Empty DataFrame
Columns: [time_start, volume, direction, tollgate_id, time_window, weekday, weekend, hour, date, volume_anterior, volume_anterior_2, media_volume, desvio_padrao, am_pm, pressure, sea_pressure, wind_direction, wind_speed, temperature, rel_humidity, precipitation]
Index: []

[0 rows x 21 columns]

In [11]:
df_test = pd.concat(df_test_list)

In [12]:
df_test.head()

time_start  volume  direction  tollgate_id          time_window  \
0  2016-10-25 00:00:00       0          0            1  [00:00:00,00:20:00)   
1  2016-10-25 00:20:00       0          0            1  [00:20:00,00:40:00)   
2  2016-10-25 00:40:00       0          0            1  [00:40:00,01:00:00)   
3  2016-10-25 01:00:00       0          0            1  [01:00:00,01:20:00)   
4  2016-10-25 01:20:00       0          0            1  [01:20:00,01:40:00)   

   weekday  weekend  hour        date  volume_anterior      ...        \
0        2        0     0  2016-10-25              0.0      ...         
1        2        0     0  2016-10-25              0.0      ...         
2        2        0     0  2016-10-25              0.0      ...         
3        2        0     1  2016-10-25              0.0      ...         
4        2        0     1  2016-10-25              0.0      ...         

   media_volume  desvio_padrao  am_pm  pressure  sea_pressure  wind_direction  \
0             0            0.0      1    1010.6        1015.6           356.0   
1             0            0.0      1    1010.6        1015.6           356.0   
2             0            0.0      1    1010.6        1015.6           356.0   
3             0            0.0      1       NaN           NaN             NaN   
4             0            0.0      1       NaN           NaN             NaN   

   wind_speed  temperature  rel_humidity  precipitation  
0         3.4         20.2          86.0            0.0  
1         3.4         20.2          86.0            0.0  
2         3.4         20.2          86.0            0.0  
3         NaN          NaN           NaN            NaN  
4         NaN          NaN           NaN            NaN  

[5 rows x 21 columns]

In [13]:
df_remove = df_test.loc[(df_test['volume'] == 0)]

df_test = df_test.drop(df_remove.index)

In [32]:
df_test.head()
df_test.to_csv("test_real.csv", index=False)

In [14]:
def feature_format():
    #pd_volume_train = pd_volume_train.set_index(['time'])
    #pd_volume_test = pd_volume_test.set_index(['time'])
    #volume_train = v_train.groupby(['time_window','tollgate_id','direction','date', 'hour']).size().reset_index().rename(columns = {0:'volume'})
    #volume_test = v_test.groupby(['time_window','tollgate_id','direction','date', 'hour']).size().reset_index().rename(columns = {0:'volume'})
    #print(volume_train)                
    x = pd.Series(df_train['time_window'].unique())
    s = pd.Series(range(len(x)),index = x.values)
    df_train['window_n'] = df_train['time_window'].map(s)
    df_test['window_n'] = df_test['time_window'].map(s)
#        print vol_test.tail()
    #volume_train['weekday'] = v_train['weekday']
    #volume_test['weekday'] = v_test['weekday']
    
    feature_train = df_train.drop('volume', axis = 1)
    feature_test = df_test.drop('volume',axis = 1)
    values_train = df_train['volume'].values
    values_test = df_test['volume'].values
    
    return feature_train, feature_test, values_train, values_test

In [15]:
feature_train, feature_test, values_train, values_test = feature_format()
feature_train.head()

time_start  direction  tollgate_id          time_window  weekday  \
0  2016-09-19 00:00:00          0            1  [00:00:00,00:20:00)        1   
1  2016-09-19 00:20:00          0            1  [00:20:00,00:40:00)        1   
2  2016-09-19 00:40:00          0            1  [00:40:00,01:00:00)        1   
3  2016-09-19 01:00:00          0            1  [01:00:00,01:20:00)        1   
4  2016-09-19 01:20:00          0            1  [01:20:00,01:40:00)        1   

   weekend  hour        date  volume_anterior  volume_anterior_2    ...     \
0        0     0  2016-09-19              0.0                0.0    ...      
1        0     0  2016-09-19             13.0                0.0    ...      
2        0     0  2016-09-19              6.0               13.0    ...      
3        0     1  2016-09-19              9.0                6.0    ...      
4        0     1  2016-09-19             10.0                9.0    ...      

   desvio_padrao  am_pm  pressure  sea_pressure  wind_direction  wind_speed  \
0       4.750439      1    1008.2        1013.2           329.0         2.8   
1       3.816630      1    1008.2        1013.2           329.0         2.8   
2       2.664583      1    1008.2        1013.2           329.0         2.8   
3       2.857738      1       NaN           NaN             NaN         NaN   
4       4.593474      1       NaN           NaN             NaN         NaN   

   temperature  rel_humidity  precipitation  window_n  
0         22.2          76.0            0.0         0  
1         22.2          76.0            0.0         1  
2         22.2          76.0            0.0         2  
3          NaN           NaN            NaN         3  
4          NaN           NaN            NaN         4  

[5 rows x 21 columns]

In [19]:
def feature_transform_split(data):
    data["precipitation"] = data[["precipitation"]].fillna(value=0)
    data["rel_humidity"] = data[["rel_humidity"]].fillna(value=50)

    data["precipitation"] = data["precipitation"].apply(lambda x: x > 0)
    data["rel_humidity"] = data["rel_humidity"].apply(lambda x: x > 90)

    data = data.drop("precipitation", axis=1)
    return data

In [47]:
def feature_transform_split_complete(key, data):
    # data = remove_exception(data)

    data["precipitation"] = data[["precipitation"]].fillna(value=0)
    data["rel_humidity"] = data[["rel_humidity"]].fillna(value=50)

    data["precipitation"] = data["precipitation"].apply(lambda x: x > 0)
    data["rel_humidity"] = data["rel_humidity"].apply(lambda x: x > 90)

    data = data.drop("precipitation", axis=1)
    # data = data.drop("rel_humidity", axis= 1)




    # data["sum"] = data["0"] + data["1"] + data["2"] + data["3"] + data["4"] + data["5"]

    #data = pd.concat([data, pd.get_dummies(data['period_num'])], axis=1)
    #data = data.drop("period_num", axis=1)

   # data = pd.concat([data, pd.get_dummies(data['holiday'])], axis=1)
    #data = data.drop("holiday", axis=1)
    #
    # data = pd.concat([data, pd.get_dummies(data['first_last_workday'])], axis=1)
    #data = data.drop("first_last_workday", axis=1)

    #data = data.drop("day_of_week", axis=1)

    if (key == 1):
        data = pd.concat([data, pd.get_dummies(data['tollgate_id'])], axis=1)
        # data["tollgate_id1"] = data['tollgate_id']
        data["direction1"] = data['direction']
    return data

In [15]:
feature_train = feature_transform_split(feature_train)

In [16]:
feature_test = feature_transform_split(feature_test)

In [16]:
feature_train.head()

time_start  direction  tollgate_id          time_window  weekday  \
0  2016-09-19 00:00:00          0            1  [00:00:00,00:20:00)        1   
1  2016-09-19 00:20:00          0            1  [00:20:00,00:40:00)        1   
2  2016-09-19 00:40:00          0            1  [00:40:00,01:00:00)        1   
3  2016-09-19 01:00:00          0            1  [01:00:00,01:20:00)        1   
4  2016-09-19 01:20:00          0            1  [01:20:00,01:40:00)        1   

   weekend  hour        date  volume_anterior  volume_anterior_2    ...     \
0        0     0  2016-09-19              0.0                0.0    ...      
1        0     0  2016-09-19             13.0                0.0    ...      
2        0     0  2016-09-19              6.0               13.0    ...      
3        0     1  2016-09-19              9.0                6.0    ...      
4        0     1  2016-09-19             10.0                9.0    ...      

   desvio_padrao  am_pm  pressure  sea_pressure  wind_direction  wind_speed  \
0       4.750439      1    1008.2        1013.2           329.0         2.8   
1       3.816630      1    1008.2        1013.2           329.0         2.8   
2       2.664583      1    1008.2        1013.2           329.0         2.8   
3       2.857738      1       NaN           NaN             NaN         NaN   
4       4.593474      1       NaN           NaN             NaN         NaN   

   temperature  rel_humidity  precipitation  window_n  
0         22.2          76.0            0.0         0  
1         22.2          76.0            0.0         1  
2         22.2          76.0            0.0         2  
3          NaN           NaN            NaN         3  
4          NaN           NaN            NaN         4  

[5 rows x 21 columns]

In [17]:
regressor_cubic = RandomForestRegressor(n_estimators = 1500, random_state = 42)

In [20]:
regressor_cubic.fit(feature_train[['weekday','volume_anterior', 'volume_anterior_2','media_volume', 'desvio_padrao', 'am_pm']], values_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1500, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [42]:
y_pred = regressor_cubic.predict(feature_test[['weekday','volume_anterior', 'volume_anterior_2','media_volume', 'desvio_padrao', 'am_pm']])y_pred = regressor_cubic.predict(feature_test[['weekday','volume_anterior', 'volume_anterior_2','media_volume', 'desvio_padrao', 'am_pm']])

In [83]:
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [84]:
mean_absolute_percentage_error(values_test, y_pred)

45.456665522996744

In [36]:
y_pred.transform("shift",1)
#pd_volume_test["volume_anterior_2"] = pd_volume_test.groupby(['direction', 'tollgate_id'])["volume"].transform("shift", 2)

AttributeError: 'numpy.ndarray' object has no attribute 'transform'

In [24]:
values_test

array([ 9, 20, 31, ..., 24, 73, 18])

In [43]:
y_pred = np.delete(y_pred, 0)
print (list(y_pred)[0])

12.600672222222219


In [74]:
y_pred[[len(y_pred+1)]] = 2

IndexError: index 1119 is out of bounds for axis 1 with size 1119

In [70]:
len(y_pred)+1

1120

In [77]:
values_test = np.delete(values_test, len(values_test)-1)

In [78]:
print (list(values_test)[4]) 

38


In [79]:
mean_squared_error(y_pred,values_test)

1124.0483407405834

In [80]:
r2_score(values_test, y_pred) 

0.2315901347694015

In [81]:
rms = sqrt(mean_squared_error(values_test, y_pred))
rms

33.52683016243235

In [85]:
values_test

array([ 10,  17,  30, ..., 108,  24,  73])

In [86]:
y_pred

array([12.60067222, 16.43      , 18.58666667, ..., 52.69133333,
       70.35311111, 31.34      ])